package com.kettle.soso.quartz.model;

import java.io.Serializable;

public class CalendarsKey implements Serializable {
    /**
     * 
     * 表字段 : qrtz_calendars.SCHED_NAME
     */
    private String schedName;

    /**
     * 
     * 表字段 : qrtz_calendars.CALENDAR_NAME
     */
    private String calendarName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table qrtz_calendars
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取  字段:qrtz_calendars.SCHED_NAME
     *
     * @return qrtz_calendars.SCHED_NAME, 
     */
    public String getSchedName() {
        return schedName;
    }

    /**
     * 设置  字段:qrtz_calendars.SCHED_NAME
     *
     * @param schedName the value for qrtz_calendars.SCHED_NAME, 
     */
    public void setSchedName(String schedName) {
        this.schedName = schedName == null ? null : schedName.trim();
    }

    /**
     * 获取  字段:qrtz_calendars.CALENDAR_NAME
     *
     * @return qrtz_calendars.CALENDAR_NAME, 
     */
    public String getCalendarName() {
        return calendarName;
    }

    /**
     * 设置  字段:qrtz_calendars.CALENDAR_NAME
     *
     * @param calendarName the value for qrtz_calendars.CALENDAR_NAME, 
     */
    public void setCalendarName(String calendarName) {
        this.calendarName = calendarName == null ? null : calendarName.trim();
    }
}