package com.kettle.soso.quartz.model;

import java.io.Serializable;

public class JobDetailsKey implements Serializable {
    /**
     * 
     * 表字段 : qrtz_job_details.SCHED_NAME
     */
    private String schedName;

    /**
     * 
     * 表字段 : qrtz_job_details.JOB_NAME
     */
    private String jobName;

    /**
     * 
     * 表字段 : qrtz_job_details.JOB_GROUP
     */
    private String jobGroup;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table qrtz_job_details
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取  字段:qrtz_job_details.SCHED_NAME
     *
     * @return qrtz_job_details.SCHED_NAME, 
     */
    public String getSchedName() {
        return schedName;
    }

    /**
     * 设置  字段:qrtz_job_details.SCHED_NAME
     *
     * @param schedName the value for qrtz_job_details.SCHED_NAME, 
     */
    public void setSchedName(String schedName) {
        this.schedName = schedName == null ? null : schedName.trim();
    }

    /**
     * 获取  字段:qrtz_job_details.JOB_NAME
     *
     * @return qrtz_job_details.JOB_NAME, 
     */
    public String getJobName() {
        return jobName;
    }

    /**
     * 设置  字段:qrtz_job_details.JOB_NAME
     *
     * @param jobName the value for qrtz_job_details.JOB_NAME, 
     */
    public void setJobName(String jobName) {
        this.jobName = jobName == null ? null : jobName.trim();
    }

    /**
     * 获取  字段:qrtz_job_details.JOB_GROUP
     *
     * @return qrtz_job_details.JOB_GROUP, 
     */
    public String getJobGroup() {
        return jobGroup;
    }

    /**
     * 设置  字段:qrtz_job_details.JOB_GROUP
     *
     * @param jobGroup the value for qrtz_job_details.JOB_GROUP, 
     */
    public void setJobGroup(String jobGroup) {
        this.jobGroup = jobGroup == null ? null : jobGroup.trim();
    }
}