package com.kettle.soso.quartz.model;

import java.io.Serializable;

public class JobDetails extends JobDetailsKey implements Serializable {
    /**
     * 
     * 表字段 : qrtz_job_details.DESCRIPTION
     */
    private String description;

    /**
     * 
     * 表字段 : qrtz_job_details.JOB_CLASS_NAME
     */
    private String jobClassName;

    /**
     * 
     * 表字段 : qrtz_job_details.IS_DURABLE
     */
    private String isDurable;

    /**
     * 
     * 表字段 : qrtz_job_details.IS_NONCONCURRENT
     */
    private String isNonconcurrent;

    /**
     * 
     * 表字段 : qrtz_job_details.IS_UPDATE_DATA
     */
    private String isUpdateData;

    /**
     * 
     * 表字段 : qrtz_job_details.REQUESTS_RECOVERY
     */
    private String requestsRecovery;

    /**
     * 
     * 表字段 : qrtz_job_details.JOB_DATA
     */
    private byte[] jobData;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table qrtz_job_details
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取  字段:qrtz_job_details.DESCRIPTION
     *
     * @return qrtz_job_details.DESCRIPTION, 
     */
    public String getDescription() {
        return description;
    }

    /**
     * 设置  字段:qrtz_job_details.DESCRIPTION
     *
     * @param description the value for qrtz_job_details.DESCRIPTION, 
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * 获取  字段:qrtz_job_details.JOB_CLASS_NAME
     *
     * @return qrtz_job_details.JOB_CLASS_NAME, 
     */
    public String getJobClassName() {
        return jobClassName;
    }

    /**
     * 设置  字段:qrtz_job_details.JOB_CLASS_NAME
     *
     * @param jobClassName the value for qrtz_job_details.JOB_CLASS_NAME, 
     */
    public void setJobClassName(String jobClassName) {
        this.jobClassName = jobClassName == null ? null : jobClassName.trim();
    }

    /**
     * 获取  字段:qrtz_job_details.IS_DURABLE
     *
     * @return qrtz_job_details.IS_DURABLE, 
     */
    public String getIsDurable() {
        return isDurable;
    }

    /**
     * 设置  字段:qrtz_job_details.IS_DURABLE
     *
     * @param isDurable the value for qrtz_job_details.IS_DURABLE, 
     */
    public void setIsDurable(String isDurable) {
        this.isDurable = isDurable == null ? null : isDurable.trim();
    }

    /**
     * 获取  字段:qrtz_job_details.IS_NONCONCURRENT
     *
     * @return qrtz_job_details.IS_NONCONCURRENT, 
     */
    public String getIsNonconcurrent() {
        return isNonconcurrent;
    }

    /**
     * 设置  字段:qrtz_job_details.IS_NONCONCURRENT
     *
     * @param isNonconcurrent the value for qrtz_job_details.IS_NONCONCURRENT, 
     */
    public void setIsNonconcurrent(String isNonconcurrent) {
        this.isNonconcurrent = isNonconcurrent == null ? null : isNonconcurrent.trim();
    }

    /**
     * 获取  字段:qrtz_job_details.IS_UPDATE_DATA
     *
     * @return qrtz_job_details.IS_UPDATE_DATA, 
     */
    public String getIsUpdateData() {
        return isUpdateData;
    }

    /**
     * 设置  字段:qrtz_job_details.IS_UPDATE_DATA
     *
     * @param isUpdateData the value for qrtz_job_details.IS_UPDATE_DATA, 
     */
    public void setIsUpdateData(String isUpdateData) {
        this.isUpdateData = isUpdateData == null ? null : isUpdateData.trim();
    }

    /**
     * 获取  字段:qrtz_job_details.REQUESTS_RECOVERY
     *
     * @return qrtz_job_details.REQUESTS_RECOVERY, 
     */
    public String getRequestsRecovery() {
        return requestsRecovery;
    }

    /**
     * 设置  字段:qrtz_job_details.REQUESTS_RECOVERY
     *
     * @param requestsRecovery the value for qrtz_job_details.REQUESTS_RECOVERY, 
     */
    public void setRequestsRecovery(String requestsRecovery) {
        this.requestsRecovery = requestsRecovery == null ? null : requestsRecovery.trim();
    }

    /**
     * 获取  字段:qrtz_job_details.JOB_DATA
     *
     * @return qrtz_job_details.JOB_DATA, 
     */
    public byte[] getJobData() {
        return jobData;
    }

    /**
     * 设置  字段:qrtz_job_details.JOB_DATA
     *
     * @param jobData the value for qrtz_job_details.JOB_DATA, 
     */
    public void setJobData(byte[] jobData) {
        this.jobData = jobData;
    }
}