package com.kettle.soso.mybatis.dal.model;

import java.io.Serializable;
import org.beans.GogoDo;

public class CreditOrganization extends GogoDo implements Serializable {
    /**
     * 生成主键
     * 表字段 : credit_organization.uuid
     */
    private String uuid;

    /**
     * 组织代号
     * 表字段 : credit_organization.organization_code
     */
    private String organizationCode;

    /**
     * 组织名称
     * 表字段 : credit_organization.organization_name
     */
    private String organizationName;

    /**
     * 组织负责人
     * 表字段 : credit_organization.organization_principal
     */
    private String organizationPrincipal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table credit_organization
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取 生成主键 字段:credit_organization.uuid
     *
     * @return credit_organization.uuid, 生成主键
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * 设置 生成主键 字段:credit_organization.uuid
     *
     * @param uuid the value for credit_organization.uuid, 生成主键
     */
    public void setUuid(String uuid) {
        this.uuid = uuid == null ? null : uuid.trim();
    }

    /**
     * 获取 组织代号 字段:credit_organization.organization_code
     *
     * @return credit_organization.organization_code, 组织代号
     */
    public String getOrganizationCode() {
        return organizationCode;
    }

    /**
     * 设置 组织代号 字段:credit_organization.organization_code
     *
     * @param organizationCode the value for credit_organization.organization_code, 组织代号
     */
    public void setOrganizationCode(String organizationCode) {
        this.organizationCode = organizationCode == null ? null : organizationCode.trim();
    }

    /**
     * 获取 组织名称 字段:credit_organization.organization_name
     *
     * @return credit_organization.organization_name, 组织名称
     */
    public String getOrganizationName() {
        return organizationName;
    }

    /**
     * 设置 组织名称 字段:credit_organization.organization_name
     *
     * @param organizationName the value for credit_organization.organization_name, 组织名称
     */
    public void setOrganizationName(String organizationName) {
        this.organizationName = organizationName == null ? null : organizationName.trim();
    }

    /**
     * 获取 组织负责人 字段:credit_organization.organization_principal
     *
     * @return credit_organization.organization_principal, 组织负责人
     */
    public String getOrganizationPrincipal() {
        return organizationPrincipal;
    }

    /**
     * 设置 组织负责人 字段:credit_organization.organization_principal
     *
     * @param organizationPrincipal the value for credit_organization.organization_principal, 组织负责人
     */
    public void setOrganizationPrincipal(String organizationPrincipal) {
        this.organizationPrincipal = organizationPrincipal == null ? null : organizationPrincipal.trim();
    }

    @Override
    public String getBoQualifiedIntfName() {
        return "com.kettle.soso.mybatis.dal.bo.CreditOrganizationBo";
    }
}