package com.kettle.soso.mybatis.dal.model;

import java.io.Serializable;
import org.beans.GogoDo;

public class CreditOrgFileCount extends GogoDo implements Serializable {
    /**
     * 生成主键
     * 表字段 : credit_org_file_count.uuid
     */
    private String uuid;

    /**
     * 组织代号
     * 表字段 : credit_org_file_count.organization_code
     */
    private String organizationCode;

    /**
     * 文件数量
     * 表字段 : credit_org_file_count.count
     */
    private Integer count;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table credit_org_file_count
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取 生成主键 字段:credit_org_file_count.uuid
     *
     * @return credit_org_file_count.uuid, 生成主键
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * 设置 生成主键 字段:credit_org_file_count.uuid
     *
     * @param uuid the value for credit_org_file_count.uuid, 生成主键
     */
    public void setUuid(String uuid) {
        this.uuid = uuid == null ? null : uuid.trim();
    }

    /**
     * 获取 组织代号 字段:credit_org_file_count.organization_code
     *
     * @return credit_org_file_count.organization_code, 组织代号
     */
    public String getOrganizationCode() {
        return organizationCode;
    }

    /**
     * 设置 组织代号 字段:credit_org_file_count.organization_code
     *
     * @param organizationCode the value for credit_org_file_count.organization_code, 组织代号
     */
    public void setOrganizationCode(String organizationCode) {
        this.organizationCode = organizationCode == null ? null : organizationCode.trim();
    }

    /**
     * 获取 文件数量 字段:credit_org_file_count.count
     *
     * @return credit_org_file_count.count, 文件数量
     */
    public Integer getCount() {
        return count;
    }

    /**
     * 设置 文件数量 字段:credit_org_file_count.count
     *
     * @param count the value for credit_org_file_count.count, 文件数量
     */
    public void setCount(Integer count) {
        this.count = count;
    }

    @Override
    public String getBoQualifiedIntfName() {
        return "com.kettle.soso.mybatis.dal.bo.CreditOrgFileCountBo";
    }
}