package com.kettle.soso.mybatis.dal.model;

import java.io.Serializable;
import org.beans.GogoDo;

public class CreditFile extends GogoDo implements Serializable {
    /**
     * 生成主键
     * 表字段 : credit_file.uuid
     */
    private String uuid;

    /**
     * 文件原始名称
     * 表字段 : credit_file.file_old_name
     */
    private String fileOldName;

    /**
     * 文件新名称
     * 表字段 : credit_file.file_new_name
     */
    private String fileNewName;

    /**
     * 文件路径
     * 表字段 : credit_file.file_path
     */
    private String filePath;

    /**
     * 文件后缀
     * 表字段 : credit_file.file_suffix
     */
    private String fileSuffix;

    /**
     * 文件类型
     * 表字段 : credit_file.file_type
     */
    private String fileType;

    /**
     * 文件大小
     * 表字段 : credit_file.size
     */
    private Integer size;

    /**
     * 文件校验值
     * 表字段 : credit_file.verify_md5
     */
    private String verifyMd5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table credit_file
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取 生成主键 字段:credit_file.uuid
     *
     * @return credit_file.uuid, 生成主键
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * 设置 生成主键 字段:credit_file.uuid
     *
     * @param uuid the value for credit_file.uuid, 生成主键
     */
    public void setUuid(String uuid) {
        this.uuid = uuid == null ? null : uuid.trim();
    }

    /**
     * 获取 文件原始名称 字段:credit_file.file_old_name
     *
     * @return credit_file.file_old_name, 文件原始名称
     */
    public String getFileOldName() {
        return fileOldName;
    }

    /**
     * 设置 文件原始名称 字段:credit_file.file_old_name
     *
     * @param fileOldName the value for credit_file.file_old_name, 文件原始名称
     */
    public void setFileOldName(String fileOldName) {
        this.fileOldName = fileOldName == null ? null : fileOldName.trim();
    }

    /**
     * 获取 文件新名称 字段:credit_file.file_new_name
     *
     * @return credit_file.file_new_name, 文件新名称
     */
    public String getFileNewName() {
        return fileNewName;
    }

    /**
     * 设置 文件新名称 字段:credit_file.file_new_name
     *
     * @param fileNewName the value for credit_file.file_new_name, 文件新名称
     */
    public void setFileNewName(String fileNewName) {
        this.fileNewName = fileNewName == null ? null : fileNewName.trim();
    }

    /**
     * 获取 文件路径 字段:credit_file.file_path
     *
     * @return credit_file.file_path, 文件路径
     */
    public String getFilePath() {
        return filePath;
    }

    /**
     * 设置 文件路径 字段:credit_file.file_path
     *
     * @param filePath the value for credit_file.file_path, 文件路径
     */
    public void setFilePath(String filePath) {
        this.filePath = filePath == null ? null : filePath.trim();
    }

    /**
     * 获取 文件后缀 字段:credit_file.file_suffix
     *
     * @return credit_file.file_suffix, 文件后缀
     */
    public String getFileSuffix() {
        return fileSuffix;
    }

    /**
     * 设置 文件后缀 字段:credit_file.file_suffix
     *
     * @param fileSuffix the value for credit_file.file_suffix, 文件后缀
     */
    public void setFileSuffix(String fileSuffix) {
        this.fileSuffix = fileSuffix == null ? null : fileSuffix.trim();
    }

    /**
     * 获取 文件类型 字段:credit_file.file_type
     *
     * @return credit_file.file_type, 文件类型
     */
    public String getFileType() {
        return fileType;
    }

    /**
     * 设置 文件类型 字段:credit_file.file_type
     *
     * @param fileType the value for credit_file.file_type, 文件类型
     */
    public void setFileType(String fileType) {
        this.fileType = fileType == null ? null : fileType.trim();
    }

    /**
     * 获取 文件大小 字段:credit_file.size
     *
     * @return credit_file.size, 文件大小
     */
    public Integer getSize() {
        return size;
    }

    /**
     * 设置 文件大小 字段:credit_file.size
     *
     * @param size the value for credit_file.size, 文件大小
     */
    public void setSize(Integer size) {
        this.size = size;
    }

    /**
     * 获取 文件校验值 字段:credit_file.verify_md5
     *
     * @return credit_file.verify_md5, 文件校验值
     */
    public String getVerifyMd5() {
        return verifyMd5;
    }

    /**
     * 设置 文件校验值 字段:credit_file.verify_md5
     *
     * @param verifyMd5 the value for credit_file.verify_md5, 文件校验值
     */
    public void setVerifyMd5(String verifyMd5) {
        this.verifyMd5 = verifyMd5 == null ? null : verifyMd5.trim();
    }

    @Override
    public String getBoQualifiedIntfName() {
        return "com.kettle.soso.mybatis.dal.bo.CreditFileBo";
    }
}