package com.kettle.soso.mybatis.dal.model;

import java.io.Serializable;
import org.beans.GogoDo;

public class FormDemo extends GogoDo implements Serializable {
    /**
     * 
     * 表字段 : count_detail.code
     */
    private String code;

    /**
     * 
     * 表字段 : count_detail.name
     */
    private String name;

    /**
     * 
     * 表字段 : count_detail.month_string
     */
    private String monthString;

    /**
     * 
     * 表字段 : count_detail.count
     */
    private Integer count;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table count_detail
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取  字段:count_detail.code
     *
     * @return count_detail.code, 
     */
    public String getCode() {
        return code;
    }

    /**
     * 设置  字段:count_detail.code
     *
     * @param code the value for count_detail.code, 
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * 获取  字段:count_detail.name
     *
     * @return count_detail.name, 
     */
    public String getName() {
        return name;
    }

    /**
     * 设置  字段:count_detail.name
     *
     * @param name the value for count_detail.name, 
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * 获取  字段:count_detail.month_string
     *
     * @return count_detail.month_string, 
     */
    public String getMonthString() {
        return monthString;
    }

    /**
     * 设置  字段:count_detail.month_string
     *
     * @param monthString the value for count_detail.month_string, 
     */
    public void setMonthString(String monthString) {
        this.monthString = monthString == null ? null : monthString.trim();
    }

    /**
     * 获取  字段:count_detail.count
     *
     * @return count_detail.count, 
     */
    public Integer getCount() {
        return count;
    }

    /**
     * 设置  字段:count_detail.count
     *
     * @param count the value for count_detail.count, 
     */
    public void setCount(Integer count) {
        this.count = count;
    }

    @Override
    public String getBoQualifiedIntfName() {
        return "com.kettle.soso.mybatis.dal.bo.FormDemoBo";
    }
}