package com.kettle.soso.hs_smc.model;

import java.io.Serializable;
import java.math.BigDecimal;

public class OrgInfo implements Serializable {
    /**
     * 机构ID
     * 表字段 : org_info.ORGID
     */
    private Long orgid;

    /**
     * 名称
     * 表字段 : org_info.ORGNAME
     */
    private String orgname;

    /**
     * 编号
     * 表字段 : org_info.ORGNO
     */
    private String orgno;

    /**
     * 层级编号
     * 表字段 : org_info.INNERNO
     */
    private String innerno;

    /**
     * 管理员
     * 表字段 : org_info.PRINCIPAL
     */
    private String principal;

    /**
     * 联系人
     * 表字段 : org_info.LINKMAN
     */
    private String linkman;

    /**
     * 
     * 表字段 : org_info.TELEPHONE
     */
    private String telephone;

    /**
     * 
     * 表字段 : org_info.FAX
     */
    private String fax;

    /**
     * 
     * 表字段 : org_info.ADDRESS
     */
    private String address;

    /**
     * 
     * 表字段 : org_info.POSTCODE
     */
    private String postcode;

    /**
     * 
     * 表字段 : org_info.EMAIL
     */
    private String email;

    /**
     * 上级机构ID
     * 表字段 : org_info.SUPERIORORG
     */
    private BigDecimal superiororg;

    /**
     * 虚拟机构标志
     * 表字段 : org_info.VIRFLG
     */
    private String virflg;

    /**
     * 机构状态. 0为正常, 1为撤销 (逻辑删除)
     * 表字段 : org_info.STATUS
     */
    private String status;

    /**
     * 机构类别
     * 表字段 : org_info.TYPE
     */
    private String type;

    /**
     * 
     * 表字段 : org_info.EXTEND1
     */
    private String extend1;

    /**
     * 
     * 表字段 : org_info.EXTEND2
     */
    private String extend2;

    /**
     * 
     * 表字段 : org_info.EXTEND3
     */
    private String extend3;

    /**
     * 
     * 表字段 : org_info.EXTEND4
     */
    private String extend4;

    /**
     * 
     * 表字段 : org_info.EXTEND5
     */
    private String extend5;

    /**
     * 
     * 表字段 : org_info.EXTEND6
     */
    private String extend6;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table org_info
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取 机构ID 字段:org_info.ORGID
     *
     * @return org_info.ORGID, 机构ID
     */
    public Long getOrgid() {
        return orgid;
    }

    /**
     * 设置 机构ID 字段:org_info.ORGID
     *
     * @param orgid the value for org_info.ORGID, 机构ID
     */
    public void setOrgid(Long orgid) {
        this.orgid = orgid;
    }

    /**
     * 获取 名称 字段:org_info.ORGNAME
     *
     * @return org_info.ORGNAME, 名称
     */
    public String getOrgname() {
        return orgname;
    }

    /**
     * 设置 名称 字段:org_info.ORGNAME
     *
     * @param orgname the value for org_info.ORGNAME, 名称
     */
    public void setOrgname(String orgname) {
        this.orgname = orgname == null ? null : orgname.trim();
    }

    /**
     * 获取 编号 字段:org_info.ORGNO
     *
     * @return org_info.ORGNO, 编号
     */
    public String getOrgno() {
        return orgno;
    }

    /**
     * 设置 编号 字段:org_info.ORGNO
     *
     * @param orgno the value for org_info.ORGNO, 编号
     */
    public void setOrgno(String orgno) {
        this.orgno = orgno == null ? null : orgno.trim();
    }

    /**
     * 获取 层级编号 字段:org_info.INNERNO
     *
     * @return org_info.INNERNO, 层级编号
     */
    public String getInnerno() {
        return innerno;
    }

    /**
     * 设置 层级编号 字段:org_info.INNERNO
     *
     * @param innerno the value for org_info.INNERNO, 层级编号
     */
    public void setInnerno(String innerno) {
        this.innerno = innerno == null ? null : innerno.trim();
    }

    /**
     * 获取 管理员 字段:org_info.PRINCIPAL
     *
     * @return org_info.PRINCIPAL, 管理员
     */
    public String getPrincipal() {
        return principal;
    }

    /**
     * 设置 管理员 字段:org_info.PRINCIPAL
     *
     * @param principal the value for org_info.PRINCIPAL, 管理员
     */
    public void setPrincipal(String principal) {
        this.principal = principal == null ? null : principal.trim();
    }

    /**
     * 获取 联系人 字段:org_info.LINKMAN
     *
     * @return org_info.LINKMAN, 联系人
     */
    public String getLinkman() {
        return linkman;
    }

    /**
     * 设置 联系人 字段:org_info.LINKMAN
     *
     * @param linkman the value for org_info.LINKMAN, 联系人
     */
    public void setLinkman(String linkman) {
        this.linkman = linkman == null ? null : linkman.trim();
    }

    /**
     * 获取  字段:org_info.TELEPHONE
     *
     * @return org_info.TELEPHONE, 
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * 设置  字段:org_info.TELEPHONE
     *
     * @param telephone the value for org_info.TELEPHONE, 
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone == null ? null : telephone.trim();
    }

    /**
     * 获取  字段:org_info.FAX
     *
     * @return org_info.FAX, 
     */
    public String getFax() {
        return fax;
    }

    /**
     * 设置  字段:org_info.FAX
     *
     * @param fax the value for org_info.FAX, 
     */
    public void setFax(String fax) {
        this.fax = fax == null ? null : fax.trim();
    }

    /**
     * 获取  字段:org_info.ADDRESS
     *
     * @return org_info.ADDRESS, 
     */
    public String getAddress() {
        return address;
    }

    /**
     * 设置  字段:org_info.ADDRESS
     *
     * @param address the value for org_info.ADDRESS, 
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * 获取  字段:org_info.POSTCODE
     *
     * @return org_info.POSTCODE, 
     */
    public String getPostcode() {
        return postcode;
    }

    /**
     * 设置  字段:org_info.POSTCODE
     *
     * @param postcode the value for org_info.POSTCODE, 
     */
    public void setPostcode(String postcode) {
        this.postcode = postcode == null ? null : postcode.trim();
    }

    /**
     * 获取  字段:org_info.EMAIL
     *
     * @return org_info.EMAIL, 
     */
    public String getEmail() {
        return email;
    }

    /**
     * 设置  字段:org_info.EMAIL
     *
     * @param email the value for org_info.EMAIL, 
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * 获取 上级机构ID 字段:org_info.SUPERIORORG
     *
     * @return org_info.SUPERIORORG, 上级机构ID
     */
    public BigDecimal getSuperiororg() {
        return superiororg;
    }

    /**
     * 设置 上级机构ID 字段:org_info.SUPERIORORG
     *
     * @param superiororg the value for org_info.SUPERIORORG, 上级机构ID
     */
    public void setSuperiororg(BigDecimal superiororg) {
        this.superiororg = superiororg;
    }

    /**
     * 获取 虚拟机构标志 字段:org_info.VIRFLG
     *
     * @return org_info.VIRFLG, 虚拟机构标志
     */
    public String getVirflg() {
        return virflg;
    }

    /**
     * 设置 虚拟机构标志 字段:org_info.VIRFLG
     *
     * @param virflg the value for org_info.VIRFLG, 虚拟机构标志
     */
    public void setVirflg(String virflg) {
        this.virflg = virflg == null ? null : virflg.trim();
    }

    /**
     * 获取 机构状态. 0为正常, 1为撤销 (逻辑删除) 字段:org_info.STATUS
     *
     * @return org_info.STATUS, 机构状态. 0为正常, 1为撤销 (逻辑删除)
     */
    public String getStatus() {
        return status;
    }

    /**
     * 设置 机构状态. 0为正常, 1为撤销 (逻辑删除) 字段:org_info.STATUS
     *
     * @param status the value for org_info.STATUS, 机构状态. 0为正常, 1为撤销 (逻辑删除)
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * 获取 机构类别 字段:org_info.TYPE
     *
     * @return org_info.TYPE, 机构类别
     */
    public String getType() {
        return type;
    }

    /**
     * 设置 机构类别 字段:org_info.TYPE
     *
     * @param type the value for org_info.TYPE, 机构类别
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * 获取  字段:org_info.EXTEND1
     *
     * @return org_info.EXTEND1, 
     */
    public String getExtend1() {
        return extend1;
    }

    /**
     * 设置  字段:org_info.EXTEND1
     *
     * @param extend1 the value for org_info.EXTEND1, 
     */
    public void setExtend1(String extend1) {
        this.extend1 = extend1 == null ? null : extend1.trim();
    }

    /**
     * 获取  字段:org_info.EXTEND2
     *
     * @return org_info.EXTEND2, 
     */
    public String getExtend2() {
        return extend2;
    }

    /**
     * 设置  字段:org_info.EXTEND2
     *
     * @param extend2 the value for org_info.EXTEND2, 
     */
    public void setExtend2(String extend2) {
        this.extend2 = extend2 == null ? null : extend2.trim();
    }

    /**
     * 获取  字段:org_info.EXTEND3
     *
     * @return org_info.EXTEND3, 
     */
    public String getExtend3() {
        return extend3;
    }

    /**
     * 设置  字段:org_info.EXTEND3
     *
     * @param extend3 the value for org_info.EXTEND3, 
     */
    public void setExtend3(String extend3) {
        this.extend3 = extend3 == null ? null : extend3.trim();
    }

    /**
     * 获取  字段:org_info.EXTEND4
     *
     * @return org_info.EXTEND4, 
     */
    public String getExtend4() {
        return extend4;
    }

    /**
     * 设置  字段:org_info.EXTEND4
     *
     * @param extend4 the value for org_info.EXTEND4, 
     */
    public void setExtend4(String extend4) {
        this.extend4 = extend4 == null ? null : extend4.trim();
    }

    /**
     * 获取  字段:org_info.EXTEND5
     *
     * @return org_info.EXTEND5, 
     */
    public String getExtend5() {
        return extend5;
    }

    /**
     * 设置  字段:org_info.EXTEND5
     *
     * @param extend5 the value for org_info.EXTEND5, 
     */
    public void setExtend5(String extend5) {
        this.extend5 = extend5 == null ? null : extend5.trim();
    }

    /**
     * 获取  字段:org_info.EXTEND6
     *
     * @return org_info.EXTEND6, 
     */
    public String getExtend6() {
        return extend6;
    }

    /**
     * 设置  字段:org_info.EXTEND6
     *
     * @param extend6 the value for org_info.EXTEND6, 
     */
    public void setExtend6(String extend6) {
        this.extend6 = extend6 == null ? null : extend6.trim();
    }
}